### ISSUE TITLE
Error: Unbound module Serialize

### ISSUE THREAD

**Issue by adnahmed** [TOTBWF/coolttviz#2]
Hi, I'm facing an error during build. 
Could you please help me here.

**Command:** `make build`

**Excepted Output:** Project is build successfully

**Actual Output:**
```
opam config exec dune -- build @install
File "bin/main.ml", line 234, characters 23-49:
234 |      let (ctx, goal) = Serialize.deserialize_goal json in
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound module Serialize
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 1
```

**Comment by favonia** [comment]
Try this
```
opam pin cooltt git@github.com:RedPRL/cooltt.git#cube-render
```
This repo depends on the (non-default) branch `cube-render` of `cooltt`. We have not merged the necessary changes into `main` yet. Hopefully it would be simpler after that. :smile:

**Comment by TOTBWF** [comment]
Yeah, you will also need to build a copy of the `cube-render` branch to get any sort of communication between `cooltt` and `coolttviz`. I would also warn you that this is still very WIP software, so there will be some funky behaviour (In particular, font rendering is not very good, especially for unicode)

**Comment by TOTBWF** [comment]
The OCaml has been banished, so I'm closing this 🙂
